### ISSUE TITLE
Issue when count > exposure in mod_pois

### ISSUE THREAD

**Issue by lmorris2** [bayesiandemography/bage#42]
I noticed some issues in `mod_pois` when the count is larger than the exposure which I thought you may be interested in.

Running this model (with the same exposure treatment as [vignettes/vig6_mortality.Rmd](https://github.com/bayesiandemography/bage/blob/01b3114ff9bb7f41117488b8cc7ea1048636e13d/vignettes/vig6_mortality.Rmd), setting min exposure to 0.5 where there is a count):

```
mod_deaths_m5 <- mod_pois(count ~ age + sex + time + region,
   data = rates,
   exposure = ~ ifelse(count > 0 & midint_pop_est == 0, 0.5, midint_pop_est)
 ) %>%
   set_prior(age ~ RW(s = 1)) %>%
   set_prior(time ~ RW(s = 1)) %>%
   set_prior(sex ~ NFix(sd = 1)) %>%
   set_prior(region ~ N(s = 1)) %>%
   set_n_draw(100) %>%
   fit()
```

Results in the following warnings/errors followed and eventually fails:

```
Warning in asMethod(object) :
  sparse->dense coercion: allocating vector of size 1.9 GiB
Warning in asMethod(object) :
  sparse->dense coercion: allocating vector of size 1.9 GiB
Warning in stats::nlminb(start = f$par, objective = f$fn, gradient = f$gr,  :
  NA/NaN function evaluation
Warning in sqrt(diag(object$cov.fixed)) : NaNs produced
Warning in sqrt(diag(object$cov.fixed)) : NaNs produced
Error in `make_scaled_eigen()`:
! Estimated precision matrix not positive definite.
Backtrace:
 1. ... %>% fit()
 3. bage:::fit.bage_mod(.)
 4. bage:::make_scaled_eigen(prec)
```

I was able to fix the issue by restricting the exposure to be no less than the count (max observed rate of 1):

```
 mod_deaths_m9 <- mod_pois(count ~ age + sex + time + region,
    data = rates,
    exposure = ~ ifelse(count > midint_pop_est, count, midint_pop_est)
  ) %>%
    set_prior(age ~ RW(s = 1)) %>%
    set_prior(time ~ RW(s = 1)) %>%
    set_prior(sex ~ NFix(sd = 1)) %>%
    set_prior(region ~ N(s = 1)) %>%
    set_n_draw(100) %>%
    fit()
```

```
Warning in asMethod(object) :
  sparse->dense coercion: allocating vector of size 1.9 GiB
Warning in asMethod(object) :
  sparse->dense coercion: allocating vector of size 1.9 GiB
```

**Comment by johnrbryant** [comment]
Hi Luke

Thank you for raising an issue! This sort of feedback is super helpful.

It seems like 'bage' is running into numerical problems with the original data. I'm wondering if there might be some cases where deaths are very high, but estimated population is very low. It might be helpful to calculate the ratio of `count` to `midint_pop_est`, and investigate cases where the ratio is very high. 

(If this is what's going on, I'm wondering if it might be helpful to add some sort of error or warning, to let users know about extreme values.)

John

**Comment by johnrbryant** [comment]
The nicest way to deal with measurement errors in 'midint_pop_est' would be to have a data model for it - ie for 'bage' to have a data model for exposure. We have just added our first data model for outcomes, with more to come in future. We will, however, add some for exposure. 

I'm thinking of adding some sort of sanity check functions to 'poputils' that users can use to screen for improbable values. So you might call 'quality_check_mortality(mydata)', which, among other things, would look for implied rates that were implausibly high.

**Comment by johnrbryant** [comment]
I'll close this issue, and open a new one in 'poputils', describing the 'quality_check' functions.

If you have any thoughts on what a good data model for exposures might look like, please let me know. Perhaps even open an issue if you're feeling keen.

Thanks again for the input.
