### ISSUE TITLE
unable to view object generated by augment method in RStudio

### ISSUE THREAD

**Issue by tayloa1** [bayesiandemography/bage#45]
The following code in RStudio:

```
mod <- mod_pois(injuries ~ age:sex + ethnicity + year,
                data = injuries,
                exposure = popn) |>
  fit()

means<- augment(mod)
View(means)
```
Generates the following error:

**Error in storage.mode(col) <- "double" : 
  'list' object cannot be coerced to type 'double'
Error in storage.mode(col) <- "double" : 
  'list' object cannot be coerced to type 'double'**

(this is not a pasting error, the error is repeated twice in the console - possible because the issue relates to two columns)

It appears that the error is due to the structure of the data in the .fitted and .expected columns

e.g.

  .fitted
1     0.25 (0.19, 0.33)

Rstudio doesn't seem to know what to do with this.

It is possible to view in console e.g. the following code will work
```
mod <- mod_pois(injuries ~ age:sex + ethnicity + year,
                data = injuries,
                exposure = popn) |>
  fit()

means<- augment(mod)
means
```
So this isn't exactly a show stopper - just reporting as discussed.

**Comment by johnrbryant** [comment]
fixed by removing `rvec.is.numeric()` method from **rvec**
