### ISSUE TITLE
Models run in 0.7.8 not forward compatible with 0.8.1

### ISSUE THREAD

**Issue by lmorris2** [bayesiandemography/bage#67]
I've just upgraded to bage 0.8.1 and noticed that models run in bage 0.7.8 cannot be interfaced with in the new version. I noticed this when I wanted to compare a model run in bage 0.7.8 with an identical model run in 0.8.1

For example:

```
> means_m34 <- mod_m34 %>%   
augment() %>%   
mutate(draws_ci(.expected))

Error in if (zero_sum) { : argument is of length zero
```

The issue seems to be with the missing zero_sum argument from model run in the earlier version, although there could be other differences between the versions too. I believe I get the same error if I try to simply print out the model object as well.

**Comment by johnrbryant** [comment]
Yes, unfortunately you're right. The model objects have acquired a few new attributes which mean that methods from version 0.8.1 won't work properly with objects from 0.7.8. You'll need to recreate the objects with version 0.8.1 for things to work. The version that's on GitHub at the moment is a bit experimental. We're in fact still tweaking the interface. It's very likely that the 'zero_sum' command will change before we put a new version of 'bage' on CRAN. (It turns that we need two different types of zero sum constraints.) 

I'll add a warning about backward compatibility before we release a version to CRAN. We're also aiming to nail down the interface very soon, and avoid any breaking changes in future (or have a proper deprecation process.) We're still in experimental mode, but we intend to move out of that early next year.

**Comment by johnrbryant** [comment]
Functions such as 'augment' and 'print' now throw an error if they encounter an object created with an old version of 'bage'. It's still necessary to recreate the objects (sorry!!) but at least it should be clearer where the problems are coming from.

We've made big changes to the internal workings of 'bage', so it would be quite tricky (and a bit risky) to try to work with the new objects and the old objects. From this point on, though, loss of backward compatibility should be very rare (and once we lose the 'experimental' tag, we'll give a lot more warning.)

Thanks for raising the issue. I really should have added that error message before I put the new version on to GitHub.

**Comment by johnrbryant** [comment]
PS. To get the new error messages, you'll need to install version 0.8.2 of 'bage', which I have just pushed to GitHub (not CRAN).
